### ISSUE TITLE
CreateSkeletons workflow can't handle bodies larger than 2GB

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/DVIDSparkServices#7]
Spark's 2GB limitation is biting me here.  I'm careful to make sure that no individual block of data is larger than 2GB (or anything close), but apparently that doesn't matter in the case of `groupByKey()`.  It appears that if any total value becomes larger than 2GB, Spark chokes.

This is the operation in question:

```python
# body_ids_and_masks is already computed and persisted at this point.
# Each element is structured like this: (body_id, (box, mask, count))
# And we want to turn it into this:
#   --> (body_id, [(box, mask, count), (box, mask, count), (box, mask, count), ...])
grouped_body_ids_and_masks = body_ids_and_masks.groupByKey()
```

The error from Spark is shown below.  I'll have to implement a workaround: Force a downsampling step before the `groupByKey()`.

OR, if we switch to dask instead of Spark, then there won't be any 2GB limitations...

```pytb
ERROR [2017-11-08 16:34:01,136] __init__ Unhandled exception in thread: 'MainThread'
ERROR [2017-11-08 16:34:01,145] __init__ Traceback (most recent call last):
  File "/groups/flyem/proj/cluster/miniforge/envs/flyem/DVIDSparkServices/DVIDSparkServices/workflow/launchworkflow.py", line 58, in <module>
    sys.exit( main() )
  File "/groups/flyem/proj/cluster/miniforge/envs/flyem/DVIDSparkServices/DVIDSparkServices/workflow/launchworkflow.py", line 55, in main
    workflow_inst.run()
  File "/groups/flyem/proj/cluster/miniforge/envs/flyem/DVIDSparkServices/DVIDSparkServices/workflow/workflow.py", line 435, in run
    self.execute()
  File "/groups/flyem/proj/cluster/miniforge/envs/flyem/DVIDSparkServices/DVIDSparkServices/workflows/CreateSkeletons.py", line 194, in execute
    persist_and_execute(grouped_body_ids_and_masks, "Grouping masks by body id", logger)
  File "/groups/flyem/proj/cluster/miniforge/envs/flyem/DVIDSparkServices/DVIDSparkServices/util.py", line 49, in persist_and_execute
    count = rdd.count()
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/rdd.py", line 1041, in count
    return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/rdd.py", line 1032, in sum
    return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/rdd.py", line 906, in fold
    vals = self.mapPartitions(func).collect()
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/rdd.py", line 809, in collect
    port = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/misc/local/spark-test/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/misc/local/spark-test/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3324 in stage 3.0 failed 2 times, most recent failure: Lost task 3324.1 in stage 3.0 (TID 76104, 10.36.101.19, executor 2): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/serializers.py", line 220, in dump_stream
    self.serializer.dump_stream(self._batched(iterator), stream)
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/serializers.py", line 139, in dump_stream
    self._write_with_length(obj, stream)
  File "/misc/local/spark-test/python/lib/pyspark.zip/pyspark/serializers.py", line 153, in _write_with_length
    raise ValueError("can not serialize object larger than 2G")
ValueError: can not serialize object larger than 2G
```

**Comment by DocSavage** [comment]
This looks like a limitation in the serializers.  I found a patch that was introduced that allows LargeObjectSerializer.  Not sure if this would solve issue if you went to this from pyspark.zip:

https://gite.lirmm.fr/yagoubi/spark/commit/bb7a173d95094b63981724c381f68a885e514cd4

**Comment by stuarteberg** [comment]
Interesting.  That patch appears to apply only to spark "broadcast" variables, and in my case the problem doesn't happen to be with one of those.

But in any case, there must be something else strange going on in my code, because I can't fathom how a single body could amount to more than 2GB of data -- COMPRESSED!  I'm debugging now.  Maybe I can visualize this problematic body (if I can figure out it's ID) in the sparse viewer to see if it is truly large, or if I have a bug on my hands.

**Comment by anshilbhansali** [comment]
I am running into this same pyspark limitation issue. Any idea how to get around it?

**Comment by stuarteberg** [comment]
I don’t recall how I solved this particular issue. Maybe I didn’t. Eventually I switched to dask instead of PySpark.
